### ISSUE TITLE
Copy-Cat

### ISSUE THREAD

**Issue by AbdalazizNezar** [CallMeGray-dot/Polar-Project#2]
cough cough, copying from other repos, cough cough.

**Comment by CallMeGray-dot** [comment]
Hello I may have copied from another github but please checkout our readme file as you are so dumb and stupid

**Comment by AbdalazizNezar** [comment]
Oh really, well your even more dumb and stupid as you call the bot yours, when in reality, it isnt.

**Comment by CallMeGray-dot** [comment]
On Thu, Jan 7, 2021 at 14:18 Abdul <notifications@github.com> wrote:

> Oh really, well your even more dumb and stupid as you call the bot yours,
> when in reality, it isnt.
>
> —
> You are receiving this because you modified the open/close state.
>
> ur so fucking stupid u do know that I only Fucking copied economy you
bitch you should learn how to mother fucking read
